title: "Junhao Yin"
theme: jekyll-theme-cayman
description: "A personal website for Junhao Yin"
paginate: 5

# Navigation links setup
navbar:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Projects"
    url: /projects/
  - title: "Courses"
    url: /courses/
  - title: "CV"
    url: /cv/
