defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

title: "Junhao Yin "
theme: jekyll-theme-cayman
 
# Navigation bar setup
navbar:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research/
  - title: "Projects"
    url: /projects/
  - title: "Courses"
    url: /courses/
  - title: "CV"
    url: /Materials/CV.pdf
